/*
 * generated by Xtext
 */
package org.argouml.xtuml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class OALUiModule extends org.argouml.xtuml.ui.AbstractOALUiModule {
	public OALUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
