package com.mentor.nucleus.bp.ui.session.adapters;
//======================================================================
//
// File: com/mentor/nucleus/bp/ui/session/adapters/AssociationsAdapter.java
//
// WARNING:      Do not edit this generated file
// Generated by: ../com.mentor.nucleus.bp.ui.tree/arc/create_generic_adapters.inc
// Version:      $Revision$
//
// (c) Copyright 2006-2014 by Mentor Graphics Corp.  All rights reserved.
//
//========================================================================
// Licensed under the Apache License, Version 2.0 (the "License"); you may not 
// use this file except in compliance with the License.  You may obtain a copy 
// of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   See the 
// License for the specific language governing permissions and limitations under
// the License.
//======================================================================== 
//
// This class is responsible for decoupling the client model entity
// class LinkParticipation_c from the tree viewer and the hierarchy
// it imposes.
//
import java.util.ArrayList;
import java.util.List;

import org.eclipse.jface.viewers.ITreeContentProvider;
import org.eclipse.jface.viewers.Viewer;
import com.mentor.nucleus.bp.core.*;
import com.mentor.nucleus.bp.core.common.*;
import com.mentor.nucleus.bp.ui.session.SessionExplorerContentProvider;
/**
 * This file adapts the meta-model entity; 'LinkParticipation_c'
 * so that it works with the Eclipse JFace user interface components.
 * <p>
 * Do not edit this class, it was created using the Project 
 * Technology MC-Java code generator product.
 * </p>
 */
public class AssociationsAdapter implements ITreeContentProvider {
	static AssociationsAdapter associationsadapter = null;
	/**
	 * Returns the adapters singleton instance. If this
	 * is the first time, the instance is created.
	 */
	public static AssociationsAdapter getInstance() {
		if (associationsadapter == null) {
			associationsadapter = new AssociationsAdapter();
		}
		return associationsadapter;
	}
	/**
	 * @see IContentProvider#inputChanged(Viewer, Object, Object)
	 * Called when the tree's input has been changed
	 */
	public void inputChanged(Viewer viewer, Object oldInput, Object newInput) {
		// Nothing to do
	}
	/**
	 * @see IContentProvider#dispose()
	 * Called when this viewer is no longer needed
	 */
	public void dispose() {
		// Nothing to dispose
	}
	/**
	 * @see ITreeContentProvider#getParent(Object)
	 * Returns the parent of this node
	 */
	public Object getParent(Object arg) {
		Instance_c result39 = Instance_c.getOneI_INSOnR2958(LinkParticipation_c
				.getOneI_LIPOnR2901(Link_c
						.getOneI_LNKOnR2902((LinkParticipation_c) arg)));
		if (result39 != null) {
			return result39;
		}
		Instance_c result40 = Instance_c.getOneI_INSOnR2958(LinkParticipation_c
				.getOneI_LIPOnR2902(Link_c
						.getOneI_LNKOnR2901((LinkParticipation_c) arg)));
		if (result40 != null) {
			return result40;
		}
		Instance_c result41 = Instance_c.getOneI_INSOnR2958(LinkParticipation_c
				.getOneI_LIPOnR2903(Link_c
						.getOneI_LNKOnR2901((LinkParticipation_c) arg)));
		if (result41 != null) {
			return result41;
		}
		Instance_c result42 = Instance_c.getOneI_INSOnR2958(LinkParticipation_c
				.getOneI_LIPOnR2903(Link_c
						.getOneI_LNKOnR2902((LinkParticipation_c) arg)));
		if (result42 != null) {
			return result42;
		}
		return null;
	}
	/**
	 * @see IStructuredContentProvider#getElements(Object)
	 * Returns the elements below this node
	 */
	public Object[] getElements(Object arg) {
		return getChildren(arg);
	}

	/**
	 * @see ITreeContentProvider#getChildren(Object)
	 * Returns the children of this node
	 */
	public Object[] getChildren(Object arg) {
		int resultSize = 0;
		Instance_c[] instances_2901_0 = Instance_c
				.getManyI_INSsOnR2958(LinkParticipation_c.getManyI_LIPsOnR2903(Link_c
						.getManyI_LNKsOnR2901((LinkParticipation_c) arg)));

		SessionExplorerContentProvider.sort(instances_2901_0);
		resultSize += instances_2901_0.length;
		Instance_c[] instances_2902_1 = Instance_c
				.getManyI_INSsOnR2958(LinkParticipation_c.getManyI_LIPsOnR2903(Link_c
						.getManyI_LNKsOnR2902((LinkParticipation_c) arg)));

		SessionExplorerContentProvider.sort(instances_2902_1);
		resultSize += instances_2902_1.length;
		Instance_c[] instances_2958_2 = Instance_c
				.getManyI_INSsOnR2958((LinkParticipation_c) arg);

		SessionExplorerContentProvider.sort(instances_2958_2);
		resultSize += instances_2958_2.length;
		Object[] result = new Object[resultSize];
		int count = 0;
		for (int i = 0; i < instances_2901_0.length; i++) {
			result[count] = instances_2901_0[i];
			count++;
		}
		for (int i = 0; i < instances_2902_1.length; i++) {
			result[count] = instances_2902_1[i];
			count++;
		}
		for (int i = 0; i < instances_2958_2.length; i++) {
			result[count] = instances_2958_2[i];
			count++;
		}
		return result;
	}
	/**
	 * @see ITreeContentProvider#hasChildren(Object)
	 * Returns true if this node has any children
	 */
	public boolean hasChildren(Object arg) {
		Instance_c[] instances_2901_0 = Instance_c
				.getManyI_INSsOnR2958(LinkParticipation_c.getManyI_LIPsOnR2903(Link_c
						.getManyI_LNKsOnR2901((LinkParticipation_c) arg)));

		if (instances_2901_0.length > 0)
			return true;
		Instance_c[] instances_2902_1 = Instance_c
				.getManyI_INSsOnR2958(LinkParticipation_c.getManyI_LIPsOnR2903(Link_c
						.getManyI_LNKsOnR2902((LinkParticipation_c) arg)));

		if (instances_2902_1.length > 0)
			return true;
		Instance_c[] instances_2958_2 = Instance_c
				.getManyI_INSsOnR2958((LinkParticipation_c) arg);

		if (instances_2958_2.length > 0)
			return true;
		return false;
	}
}
