package com.mentor.nucleus.bp.ui.session.adapters;
//======================================================================
//
// File: com/mentor/nucleus/bp/ui/session/adapters/ComponentInstancesAdapter.java
//
// WARNING:      Do not edit this generated file
// Generated by: ../com.mentor.nucleus.bp.ui.tree/arc/create_generic_adapters.inc
// Version:      $Revision$
//
// (c) Copyright 2006-2014 by Mentor Graphics Corp.  All rights reserved.
//
//========================================================================
// Licensed under the Apache License, Version 2.0 (the "License"); you may not 
// use this file except in compliance with the License.  You may obtain a copy 
// of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   See the 
// License for the specific language governing permissions and limitations under
// the License.
//======================================================================== 
//
// This class is responsible for decoupling the client model entity
// class ComponentInstance_c from the tree viewer and the hierarchy
// it imposes.
//
import java.util.ArrayList;
import java.util.List;

import org.eclipse.jface.viewers.ITreeContentProvider;
import org.eclipse.jface.viewers.Viewer;
import com.mentor.nucleus.bp.core.*;
import com.mentor.nucleus.bp.core.common.*;
import com.mentor.nucleus.bp.ui.session.SessionExplorerContentProvider;
/**
 * This file adapts the meta-model entity; 'ComponentInstance_c'
 * so that it works with the Eclipse JFace user interface components.
 * <p>
 * Do not edit this class, it was created using the Project 
 * Technology MC-Java code generator product.
 * </p>
 */
public class ComponentInstancesAdapter implements ITreeContentProvider {
	static ComponentInstancesAdapter componentinstancesadapter = null;
	/**
	 * Returns the adapters singleton instance. If this
	 * is the first time, the instance is created.
	 */
	public static ComponentInstancesAdapter getInstance() {
		if (componentinstancesadapter == null) {
			componentinstancesadapter = new ComponentInstancesAdapter();
		}
		return componentinstancesadapter;
	}
	/**
	 * @see IContentProvider#inputChanged(Viewer, Object, Object)
	 * Called when the tree's input has been changed
	 */
	public void inputChanged(Viewer viewer, Object oldInput, Object newInput) {
		// Nothing to do
	}
	/**
	 * @see IContentProvider#dispose()
	 * Called when this viewer is no longer needed
	 */
	public void dispose() {
		// Nothing to dispose
	}
	/**
	 * @see ITreeContentProvider#getParent(Object)
	 * Returns the parent of this node
	 */
	public Object getParent(Object arg) {
		Component_c result21 = Component_c
				.getOneC_COnR2955((ComponentInstance_c) arg);
		if (result21 != null) {
			return result21;
		}
		ComponentInstance_c result22 = ComponentInstance_c
				.getOneI_EXEOnR2974(ComponentInstanceContainer_c
						.getOneI_CINOnR2975((ComponentInstance_c) arg));
		if (result22 != null) {
			return result22;
		}
		return null;
	}
	/**
	 * @see IStructuredContentProvider#getElements(Object)
	 * Returns the elements below this node
	 */
	public Object[] getElements(Object arg) {
		return getChildren(arg);
	}

	/**
	 * @see ITreeContentProvider#getChildren(Object)
	 * Returns the children of this node
	 */
	public Object[] getChildren(Object arg) {
    int resultSize = 0;
    _c [] classes_2960_0 = 
(ComponentInstance_c)arg)
;


    if (((ComponentInstance_c)arg).getRealizedby() == null) {
      resultSize += classes_2960_0.length;
    }
    Port_c [] ports_2955_1 = 
Port_c.getManyC_POsOnR4010(
Component_c.getManyC_CsOnR2955(
(ComponentInstance_c)arg)
)
;


    	        SessionExplorerContentProvider.sort(ports_2955_1);
    resultSize += ports_2955_1.length;
    Port_c [] ports_2963_2 = 
Port_c.getManyC_POsOnR4010(
Component_c.getManyC_CsOnR4201(
ComponentReference_c.getManyCL_ICsOnR2963(
(ComponentInstance_c)arg)
)
)
;


    	        SessionExplorerContentProvider.sort(ports_2963_2);
    resultSize += ports_2963_2.length;
    Package_c [] packages_2955_3 = 
Package_c.getManyEP_PKGsOnR8001(
PackageableElement_c.getManyPE_PEsOnR8003(
Component_c.getManyC_CsOnR2955(
(ComponentInstance_c)arg)
)
      , new ClassQueryInterface_c() {
							public boolean evaluate(Object candidate) {
								return ((Package_c)candidate).Isexecutingorownsexecutableelements() == true;
							}
						}
)
;


    	        SessionExplorerContentProvider.sort(packages_2955_3);
    if (((ComponentInstance_c)arg).getRealizedby() == null) {
      resultSize += packages_2955_3.length;
    }
    Package_c [] packages_2963_4 = 
Package_c.getManyEP_PKGsOnR8001(
PackageableElement_c.getManyPE_PEsOnR8003(
Component_c.getManyC_CsOnR4201(
ComponentReference_c.getManyCL_ICsOnR2963(
(ComponentInstance_c)arg)
)
)
      , new ClassQueryInterface_c() {
							public boolean evaluate(Object candidate) {
								return ((Package_c)candidate).Isexecutingorownsexecutableelements() == true;
							}
						}
)
;


    	        SessionExplorerContentProvider.sort(packages_2963_4);
    if (((ComponentInstance_c)arg).getRealizedby() == null) {
      resultSize += packages_2963_4.length;
    }
    FunctionPackage_c [] functionpackages_2955_5 = 
FunctionPackage_c.getManyS_FPKsOnR29(
Domain_c.getManyS_DOMsOnR4204(
DomainAsComponent_c.getManyCN_DCsOnR4204(
Component_c.getManyC_CsOnR2955(
(ComponentInstance_c)arg)
)
)
)
;


    	        SessionExplorerContentProvider.sort(functionpackages_2955_5);
    if (((ComponentInstance_c)arg).getRealizedby() == null) {
      resultSize += functionpackages_2955_5.length;
    }
    FunctionPackage_c [] functionpackages_2963_6 = 
FunctionPackage_c.getManyS_FPKsOnR29(
Domain_c.getManyS_DOMsOnR4204(
DomainAsComponent_c.getManyCN_DCsOnR4204(
Component_c.getManyC_CsOnR4201(
ComponentReference_c.getManyCL_ICsOnR2963(
(ComponentInstance_c)arg)
)
)
)
)
;


    	        SessionExplorerContentProvider.sort(functionpackages_2963_6);
    if (((ComponentInstance_c)arg).getRealizedby() == null) {
      resultSize += functionpackages_2963_6.length;
    }
    ComponentInstance_c [] componentinstances_2974_7 = 
ComponentInstance_c.getManyI_EXEsOnR2975(
ComponentInstanceContainer_c.getManyI_CINsOnR2974(
(ComponentInstance_c)arg)
)
;


    if (((ComponentInstance_c)arg).getRealizedby() == null) {
      resultSize += componentinstances_2974_7.length;
    }
    Object [] result = new Object [resultSize];
    int count = 0;
    if (((ComponentInstance_c)arg).getRealizedby() == null) {
    for (int i = 0 ; i < classes_2960_0.length ; i++) {
      result[count] = classes_2960_0[i];
      count++;
    }
    }
    for (int i = 0 ; i < ports_2955_1.length ; i++) {
      result[count] = ports_2955_1[i];
      count++;
    }
    for (int i = 0 ; i < ports_2963_2.length ; i++) {
      result[count] = ports_2963_2[i];
      count++;
    }
    if (((ComponentInstance_c)arg).getRealizedby() == null) {
    for (int i = 0 ; i < packages_2955_3.length ; i++) {
      result[count] = packages_2955_3[i];
      count++;
    }
    }
    if (((ComponentInstance_c)arg).getRealizedby() == null) {
    for (int i = 0 ; i < packages_2963_4.length ; i++) {
      result[count] = packages_2963_4[i];
      count++;
    }
    }
    if (((ComponentInstance_c)arg).getRealizedby() == null) {
    for (int i = 0 ; i < functionpackages_2955_5.length ; i++) {
      result[count] = functionpackages_2955_5[i];
      count++;
    }
    }
    if (((ComponentInstance_c)arg).getRealizedby() == null) {
    for (int i = 0 ; i < functionpackages_2963_6.length ; i++) {
      result[count] = functionpackages_2963_6[i];
      count++;
    }
    }
    if (((ComponentInstance_c)arg).getRealizedby() == null) {
    for (int i = 0 ; i < componentinstances_2974_7.length ; i++) {
      result[count] = componentinstances_2974_7[i];
      count++;
    }
    }
    return result;
  }
	/**
	 * @see ITreeContentProvider#hasChildren(Object)
	 * Returns true if this node has any children
	 */
	public boolean hasChildren(Object arg) {
    _c [] classes_2960_0 = 
(ComponentInstance_c)arg)
;


    if (((ComponentInstance_c)arg).getRealizedby() == null) {
    if (classes_2960_0.length > 0) return true;
    }
    Port_c [] ports_2955_1 = 
Port_c.getManyC_POsOnR4010(
Component_c.getManyC_CsOnR2955(
(ComponentInstance_c)arg)
)
;


    if (ports_2955_1.length > 0) return true;
    Port_c [] ports_2963_2 = 
Port_c.getManyC_POsOnR4010(
Component_c.getManyC_CsOnR4201(
ComponentReference_c.getManyCL_ICsOnR2963(
(ComponentInstance_c)arg)
)
)
;


    if (ports_2963_2.length > 0) return true;
    Package_c [] packages_2955_3 = 
Package_c.getManyEP_PKGsOnR8001(
PackageableElement_c.getManyPE_PEsOnR8003(
Component_c.getManyC_CsOnR2955(
(ComponentInstance_c)arg)
)
      , new ClassQueryInterface_c() {
							public boolean evaluate(Object candidate) {
								return ((Package_c)candidate).Isexecutingorownsexecutableelements() == true;
							}
						}
)
;


    if (((ComponentInstance_c)arg).getRealizedby() == null) {
    if (packages_2955_3.length > 0) return true;
    }
    Package_c [] packages_2963_4 = 
Package_c.getManyEP_PKGsOnR8001(
PackageableElement_c.getManyPE_PEsOnR8003(
Component_c.getManyC_CsOnR4201(
ComponentReference_c.getManyCL_ICsOnR2963(
(ComponentInstance_c)arg)
)
)
      , new ClassQueryInterface_c() {
							public boolean evaluate(Object candidate) {
								return ((Package_c)candidate).Isexecutingorownsexecutableelements() == true;
							}
						}
)
;


    if (((ComponentInstance_c)arg).getRealizedby() == null) {
    if (packages_2963_4.length > 0) return true;
    }
    FunctionPackage_c [] functionpackages_2955_5 = 
FunctionPackage_c.getManyS_FPKsOnR29(
Domain_c.getManyS_DOMsOnR4204(
DomainAsComponent_c.getManyCN_DCsOnR4204(
Component_c.getManyC_CsOnR2955(
(ComponentInstance_c)arg)
)
)
)
;


    if (((ComponentInstance_c)arg).getRealizedby() == null) {
    if (functionpackages_2955_5.length > 0) return true;
    }
    FunctionPackage_c [] functionpackages_2963_6 = 
FunctionPackage_c.getManyS_FPKsOnR29(
Domain_c.getManyS_DOMsOnR4204(
DomainAsComponent_c.getManyCN_DCsOnR4204(
Component_c.getManyC_CsOnR4201(
ComponentReference_c.getManyCL_ICsOnR2963(
(ComponentInstance_c)arg)
)
)
)
)
;


    if (((ComponentInstance_c)arg).getRealizedby() == null) {
    if (functionpackages_2963_6.length > 0) return true;
    }
    ComponentInstance_c [] componentinstances_2974_7 = 
ComponentInstance_c.getManyI_EXEsOnR2975(
ComponentInstanceContainer_c.getManyI_CINsOnR2974(
(ComponentInstance_c)arg)
)
;


    if (((ComponentInstance_c)arg).getRealizedby() == null) {
    if (componentinstances_2974_7.length > 0) return true;
    }
    return false;
  }
}
